---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-repo-test-dot-hello-world
  namespace: wego-system
spec:
  chart:
    spec:
      chart: ./hello-world
      sourceRef:
        kind: GitRepository
        name: external-repo-test
  interval: 5m0s

