---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nginx
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: nginx
  url: ssh://git@github.com/wkp-example-org/nginx.git


---
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx
  namespace: wego-system
spec:
  interval: 5m0s
  path: ./targets/kind-kind/kind-kind-gitops-runtime.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx
  validation: client


---
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx
  namespace: wego-system
spec:
  interval: 5m0s
  path: ./apps/kind-kind-nginx/kind-kind-nginx-gitops-runtime.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx
  validation: client

